### ISSUE TITLE
球物件大小測試，重力數值測試

### ISSUE THREAD

**Issue by bullyee** [bullyee/UnityFinal#2]
由於球物件大小會嚴重影響遊戲性，希望 @ck10800766 在建模完成後能進入遊戲中測試，直接將模型匯入prefab中，調整大小並試玩，直到遊戲玩起來不會太彆扭。
prefab檔案儲存在下列路徑 `Assets\Prefabs\ball1.prefab` \~ `Assets\Prefabs\ball_10.prefab`

**Comment by ck10800766** [comment]
你要確定我會用欸

**Comment by bullyee** [comment]
不會用可以學，不難
